#docker-compose up -d
version: '3.8'

services:
  selenium:
    image: selenium/standalone-firefox:latest
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - selenium-net

  app:
    build: .
    volumes:
      - ./config:/app/config
    ports:
      - "5000:5000"
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    depends_on:
      - selenium
    networks:
      - selenium-net

networks:
  selenium-net:
    driver: bridge